// I testi visibili, in un posto solo come strings.xml dell'app Android.
const pl = (n: number, one: string, other: string) => `${n === 1 ? one : other} · ${n}`
export const t = {
  summary: {
    waiting: (n: number) => pl(n, 'Ti aspetta', 'Ti aspettano'), finished: (n: number) => pl(n, 'Ha finito', 'Hanno finito'),
    working: (n: number) => pl(n, 'Al lavoro', 'Al lavoro'), still: (n: number) => pl(n, 'Ferma', 'Ferme'),
  } as Record<string, (n: number) => string>,
  closed: (n: number) => pl(n, 'Chiusa', 'Chiuse'), closedCat: (n: number) => `Chiuse · ${n}`, closedMore: (n: number) => `e altre ${n}`,
  outsideTitle: 'Fuori dalle sessioni', outsideSub: 'Quello che non sta in una sessione aperta',
  goal: 'Obiettivo', open: 'Apri i passaggi', close: 'Chiudi i passaggi',
  groups: { waiting: 'Ti aspetta', working: 'Al lavoro', idle: 'Ferma', closed: 'Chiuse' } as Record<string, string>,
  states: { waiting: 'domanda', busy: 'al lavoro', awaiting: 'in attesa', idle: 'ferma', gone: 'chiusa' } as Record<string, string>,
  // La «d» eufonica solo davanti alla stessa vocale (Preposition.kt): «Scrivi ad atlas-shop», «Scrivi a orbit-docs».
  writeTo: (name: string) => (name === 'master' ? 'Scrivi alla master' : `Scrivi ${/^[aàá]/i.test(name.trimStart()) ? 'ad' : 'a'} ${name}`),
  send: 'Invia', use: 'Usa', next: 'Prossimi', pick: 'Scegli una sessione dalla home',
  quota5h: (p: number) => `5h ${p}%`, ctx: (p: number) => `ctx ${p}%`, week: (p: number) => `sett. ${p}%`,
  stale: 'dato vecchio', demo: 'Dati di prova', quotaLineWindow: '5h',
  adviceTag: 'consigliato', adviceDot: "C'è un consiglio per modello ed effort",
  adviceCost: (n: string) => `Sta lavorando: cambiare adesso ricarica circa ${n} token di cache. Conviene al prossimo compito.`,
  approvalsGroup: (n: number) => `Da approvare · ${n}`, approvalProd: 'Produzione', approvalWhat: 'Esce', approvalWhere: 'Dove',
  approvalAsked: 'Chiesto', approve: 'Approva', approveProdTitle: "Approvi l'uscita in produzione?", approveTitle: (x: string) => `Approvi «${x}»?`,
  approveText: (title: string, what: string, where: string) => `${title}: ${what}, verso ${where}.`, approveNote: 'Nota per la sessione (facoltativa)',
  ctxHandoffClear: 'Handoff, poi /clear', ctxHandoffClearSub: 'Scrive il punto in docs, poi svuota il contesto a turno finito',
  ctxCompactSub: '/compact: riassume e tiene il filo', ctxWiderSub: 'Stesso modello, più spazio',
  ctxHandoffClearPrompt: "Scrivi l'handoff con /fable-director:handoff --here.",
  ctxNudge: (p: number) => `Contesto al ${p}%`, ctxNudgeSub: 'Handoff, poi /clear', ctxNudgeGo: 'Fallo',
  decisionSave: 'Salva come decisione', decisionSub: 'La master la scrive nella sua memoria: la leggono il giro novità e le sessioni.',
  decisionFor: 'Vale per', decisionAll: 'Tutti i progetti', decisionOk: 'Salva', decisionNew: 'Salva una decisione',
  cleanupOpen: 'aperta', cleanupFinished: 'ha finito il compito', cleanupFinishedAt: (hm: string) => `ha finito il compito alle ${hm}`,
  cleanupAttached: 'Finestra aperta sul PC: si chiude da lì',
  cleanupDuplicate: (of: string) => `stessa conversazione di ${of}`, cleanupDupTag: 'Doppione', cleanupClose: (n: string) => `Chiudi ${n}`,
  closeTitle: (n: string) => `Chiudere ${n}?`, closeKeep: 'Lascia aperta', closeOk: (n: string) => `Chiudi ${n}`,
  closeWorking: (n: string) => `${n} è aperta e sta lavorando.`, closeStill: (n: string) => `${n} è aperta e ferma.`,
  closeFinished: (n: string) => `${n} è aperta e ferma: ha finito il compito.`,
  closeFinishedAt: (n: string, hm: string) => `${n} è aperta e ferma: ha finito il compito alle ${hm}.`,
  closeDuplicate: (n: string, of: string) => `${n} è aperta: stessa conversazione di ${of}.`,
  closeWhat: ['riceve /exit e si chiude', 'esce dall\'elenco delle aperte e va in «Chiuse»', 'si può riaprire da «Chiuse»'], dropHere: 'Rilascia per allegare', approved: 'Approvato', decisionSent: 'Decisione mandata alla master', fileDemo: 'con i dati di prova non ci sono file', fileOpening: (n: string) => `apro ${n}`, relayConnecting: 'Collegamento al PC', relayDown: 'PC non raggiungibile, riprovo', noAnswer: 'il PC non ha risposto', updated: (h: string) => `${h} · aggiornato ora`,
  homeLast: (hm: string) => `Ultimo esito · ${hm}`, homeLastBare: 'Ultimo esito', listen: 'Ascolta',
  openConversation: 'Apri la conversazione', forYou: 'Per te', stepHint: 'Clic: nel campo · doppio clic: invia subito',
  fyContext: (name: string, p: number) => `Contesto di ${name} al ${p}%`, fyContextDetail: 'Conviene un handoff prima di continuare',
  fyHandoff: 'Handoff e riavvio', fyQuestion: (n: string) => `${n} ti chiede`, fyFinished: (n: string) => `${n} ha finito`,
  fyNightQueued: (n: number) => `Notte: ${n} in coda`, fyNightEmpty: 'Notte: niente in coda', fyNightDetail: 'Puoi lasciare un lavoro per stanotte',
  fyNext: (p: string) => `${p} · prossimo passo`, fyScheduled: (n: number) => (n === 1 ? '1 messaggio programmato' : `${n} messaggi programmati`),
  fyScheduledDetail: (hm: string) => `Il primo parte alle ${hm}`,
  fyAnswer: 'Rispondi', fyAdd: 'Aggiungi', fyStart: 'Avvia', fySee: 'Vedi', fyOpen: 'Apri',
  nightTitle: 'Aggiungi alla notte', nightProject: 'Progetto', nightPrompt: 'Cosa deve fare stanotte', nightAdd: 'Aggiungi', fyMore: (n: number) => `+${n} altre`,
  quota: (a: string, h5: number, w7: number) => `${a} ${h5}% · sett. ${w7}%`, quotaOld: (a: string) => `${a} · non aggiornata`,
  copy: 'Copia', readAloud: 'Leggi ad alta voce', stopReading: 'Ferma la lettura', outcomeLabel: 'Esito', textCut: 'testo accorciato dal PC',
  turnTokens: (n: number) => `${n} token scritti`, thinking: 'sta pensando',
  stepsCount: (n: number) => (n === 1 ? '1 passaggio' : `${n} passaggi`), stepsFailed: (n: number) => (n === 1 ? '1 fallito' : `${n} falliti`),
  origin: { pc: 'dal PC', watch: "dall'orologio", phone: 'dal telefono', web: 'dalla web app' } as Record<string, string>,
  chatStatus: {
    scheduled: (hm: string) => `parte alle ${hm}`, offline: () => 'senza rete, parte appena torna', uploading: () => "carico l'allegato",
    sending: () => 'invio', sent: () => 'inviato al PC', uncertain: () => 'in attesa del PC', failed: () => 'non consegnato',
    delivered: () => 'consegnato alla sessione', queued: () => 'in coda', working: () => 'preso in carico', done: () => 'elaborato',
  } as Record<string, (hm: string) => string>,
  questionHighRisk: "Rischio alto: tieni premuta l'opzione per rispondere", questionHold: 'Tieni premuto per confermare',
  chatAboutThis: 'Parliamone', allowAll: 'Consenti tutto', answerFree: 'Rispondi con parole tue',
  boxOpen: (x: string) => `Apri ${x}`, boxClose: (x: string) => `Chiudi ${x}`, boxAppend: 'Accoda nel campo', then: 'e poi',
  recurring: 'Ricorrenti', recurringOpen: 'Azioni ricorrenti', attach: 'Allega', attachGallery: 'Foto dalla galleria', attachCamera: 'Scatta una foto',
  attachFile: 'File', removeImage: "Togli l'immagine", reopen: 'Riapri', stop: 'Ferma', masterPlaceholder: 'Scrivi alla master',
  slashConfirmTitle: (c: string, n: string) => `Mandare /${c} a ${n}?`, slashConfirmClear: 'La conversazione della sessione si svuota: il contesto riparte da zero.',
  codeLabel: 'segue un blocco di codice', readingNow: 'IN LETTURA', readingOpen: (n: string) => `Torna a ${n}`,
  rateChange: (r: string) => `Velocità di lettura ${r}: tocca per cambiarla`, voiceChange: (v: string) => `Cambia voce, ora: ${v}`, voiceDefault: 'Predefinita del telefono',
  tabletState: { waiting: 'ti aspetta', finished: 'ha finito', working: 'al lavoro', still: 'ferma' } as Record<string, string>,
  tabletClose: (n: string) => `Togli ${n} dalle colonne`, tabletHomeLeft: 'Porta la home a sinistra', tabletHomeRight: 'Porta la home a destra',
  tabletResetWidths: 'Colonne di nuovo uguali', tabletDeskEmpty: 'Tocca una sessione nella home per aprirla qui; ne stanno fino a quattro, affiancate.',
  summaryTitle: 'Master', summaryOpen: (n: number) => `${n}\u00A0${n === 1 ? 'aperta' : 'aperte'}`, search: 'Cerca', menu: 'Menu',
  updatedNow: 'aggiornato ora', updatedAgo: (m: number) => `aggiornato ${m}\u00A0min fa`, menuPc: 'PC',
  menuConnected: (host: string, upd: string) => `Collegato a ${host} · ${upd}`, quotaLineStale: 'non aggiornata',
  badgePersonal: 'account personale', badgeWork: 'account di lavoro',
  menuLaunch: 'Lancia una sessione', menuLaunchSub: 'Un progetto, con il primo messaggio', menuRegister: 'Registro',
  menuRegisterSub: 'Stanotte, i giorni, la coda della notte', menuQuadro: 'Utilizzo e limiti', menuQuadroSub: 'Finestre di 5 ore e settimana, ritmo',
  menuSearch: 'Cerca nelle conversazioni', menuSearchSub: 'Messaggi, esiti e registro', settingsTitle: 'Impostazioni',
  launch: 'Lancia', launchProject: 'Progetto', launchFirst: 'Primo messaggio', launchRecent: 'Recenti', launchOpen: 'Apri',
  regTonight: 'Stanotte', regAdd: 'Aggiungi', regQueueEmpty: 'Nessun lavoro in coda', regQueued: (n: number) => (n === 1 ? '1 lavoro in coda' : `${n} lavori in coda`),
  regToday: 'Oggi', regYesterday: 'Ieri', regQuota: 'Quota', regMinutes: (n: number) => `${n} min`, regProjects: (n: number) => (n === 1 ? '1 progetto' : `${n} progetti`),
  diaryEmpty: 'Il diario arriva alle 20:00', nightRunning: (x: string) => `In corso: ${x}`, nightStarted: 'partito', nightRemove: 'Togli',
  nightUpdatePc: 'Aggiorna claude-master sul PC per gestire la coda da qui', nightAddTitle: 'Aggiungi alla notte',
  ovQuota: 'Quota', ovWork: 'Lavoro', ovNoQuota: 'Nessuna lettura della quota per ora', ovFiveHours: '5 ore',
  ovWeek: (p: number) => `settimana ${p}%`, ovWeekReset: (p: number, when: string) => `settimana ${p}% · ${when}`,
  ovPace: (p: number, hm: string) => `a questo ritmo ${p}% alle ${hm}`, ovNow: 'Adesso', ovNoneLive: 'Nessuna sessione aperta',
  ovQuestions: 'Ti aspettano', ovContext: 'Contesto', ovToday: 'Oggi', ovNight: 'Notte', quotaResetsAt: (hm: string) => `si azzera alle ${hm}`,
  quotaOldWord: 'dato vecchio', staleData: (m: number) => `dati di ${m} min fa`,
  ovUpdatedNow: (h: string) => `aggiornato ora · ${h}`, ovUpdatedAgo: (m: number, h: string) => `aggiornato ${m} min fa · ${h}`,
  ovStale: (m: number, h: string) => `PC fermo da ${m} min · ${h}`,
  searchHint: 'Cerca nei messaggi mandati, negli esiti e nel registro', searchHintAll: 'Cerca nelle conversazioni di tutte le sessioni',
  searchNone: 'Nessun risultato', searchClosed: 'chiusa', searchMore: 'Ci sono altri risultati: aggiungi una parola per restringere.',
  secLink: 'Collegamento', secReading: 'Lettura ad alta voce', secInfo: 'Informazioni',
  devPhone: 'Telefono', devWatch: 'Orologio', devTablet: 'Tablet', devChromebook: 'Chromebook', devOther: 'Dispositivo', devPc: 'PC',
  devThis: 'questo', devUpdatedNow: 'aggiornato ora', devUpdatedAgo: (m: number) => `${m} min fa`, devDetails: (n: string) => `${n}: dettagli`,
  devCount: (n: number) => `${n}\u00A0${n === 1 ? 'dispositivo' : 'dispositivi'}`, devSeenNow: 'ora', devSeenNever: 'mai', devSeenNeverLong: 'mai letto',
  devSeenAgo: (x: string) => `letto ${x} fa`, devHint: "Tocca un dispositivo per i dettagli · cifrato da un capo all'altro",
  factKind: 'Tipo', factSeen: 'Ultima lettura', factPairedTo: 'Abbinato a', factUpdated: 'Ultimo aggiornamento', factUpdatedNow: 'ora',
  factOpen: 'Sessioni aperte', factQuotaNone: 'nessun dato', factQuotaStale: (q: string) => `${q} · dato vecchio`, factChannel: 'Canale',
  channelFirebase: 'cifrato, attraverso Firebase', channelLocal: 'sul PC, senza rete in mezzo', channelDemo: 'dati di prova, nessun PC collegato',
  chipConnected: 'collegato', voice: 'Voce', voiceTry: 'Prova', speechRate: 'Velocità di lettura', rateHint: 'Anche dalla pillola accanto a ■ mentre legge',
  versionTitle: 'Versione', webVersion: (v: string) => `${v} · web app`, voiceSample: 'Questa è la voce che legge le risposte delle sessioni.',
  closeWord: 'Chiudi',
  elsewhereWaiting: (n: string) => `${n} ti aspetta`, elsewhereWaitingMany: (n: number) => `${n} sessioni ti aspettano`, elsewhereReply: 'Rispondi',
  elsewhereFinished: (n: string) => `${n} ha finito`, elsewhereOpen: 'Apri',
  queueTitle: 'Ti aspettano', queueEmpty: 'Nessuno ti aspetta', queueAge: (x: string) => `da ${x}`, queuePosition: (i: number, n: number) => `${i} di ${n}`,
  queuePrev: 'Domanda precedente', queueNext: 'Domanda successiva',
  tabletQuotaLabel: 'Quota 5h', tabletWeekLabel: 'Settimana', tabletNowPct: (p: number) => `ora\u00A0${p}%`,
  tabletForecast: (p: number, hm: string) => `Al ritmo di adesso arrivi al\u00A0${p}% quando riparte, alle\u00A0${hm}`,
  tabletForecastFlat: (hm: string) => `Ferma da un po': riparte alle\u00A0${hm}`,
  tabletForecastNone: (hm: string) => `Il ritmo si vede dalla seconda lettura; riparte alle\u00A0${hm}`,
  tabletForecastStale: (hm: string) => `Dato vecchio: la previsione torna col prossimo aggiornamento; riparte alle\u00A0${hm}`,
  tabletWeekForecast: (p: number, when: string) => `Allo stesso ritmo: ${p}% al rinnovo di\u00A0${when}`, tabletWeekReset: (when: string) => `Rinnovo\u00A0${when}`,
  tabletInspTitle: 'Sessione', tabletInspProject: 'progetto', tabletInspAccount: 'account', tabletInspOpened: 'aperta da', tabletInspTurn: 'turno',
  tabletInspTurnNone: 'fermo', tabletInspModel: 'modello', tabletInspPriority: 'priorità', tabletPriorityActive: 'bassa', tabletPriorityOffered: 'bassa, proposta',
  tabletInspContext: 'contesto', tabletInspPrompts: 'prompt oggi', tabletInspCommits: 'commit oggi', tabletInspToday: 'Cronologia di oggi',
  tabletInspTodayLoading: 'Chiedo la cronologia al PC', tabletInspTodayNone: 'Niente ancora oggi',
  tabletKind: { commit: 'commit', prompt: 'prompt', test: 'test', outcome: 'esito', task: 'compito' } as Record<string, string>,
  tabletDetails: 'Dettagli della sessione a destra', tabletDetailsSub: 'Progetto, turno, contesto e cronologia di oggi della prima colonna',
  soon: 'Questa pagina arriva nel prossimo passo.',
  home: 'Casa', dockMaster: 'MASTER', dockListen: "Ascolta l'ultimo esito della master", dockConversation: 'Apri la conversazione della master', dockCollapse: 'Riduci la master', more: 'Altro', cancel: 'Annulla',
  notes: { goal: 'Obiettivo', lowPriority: 'bassa priorità', lowPriorityOffered: 'bassa priorità proposta', noWindow: 'senza finestra' },
  modelTitle: 'Modello', effortTitle: 'Effort', choiceThisSession: 'Vale solo per questa sessione',
  quotaResetDesc: (p: number, r: string) => `Quota delle 5 ore al ${p}%, si azzera ${r}`,
  follow: 'Segui', unfollow: 'Non seguire', followSub: 'Una notifica quando finisce un turno', unfollowSub: 'Niente più notifiche a fine turno',
  askMaster: 'Fai controllare alla master', askMasterSub: 'La legge e ti risponde nella sua chat',
  askMasterPrompt: (n: string) => `Controlla la sessione ${n} e dimmi in breve a che punto è e se serve qualcosa da me.`,
  openInClaude: 'Apri in Claude', openInClaudeSub: "Continua nell'app Claude",
  menuExit: 'Chiudi la sessione', menuExitSub: 'Manda /exit, dopo una conferma',
  slashConfirmOk: 'Manda',
  ctxTitle: (p: number) => `Contesto ${p}%`, ctxHandoff: "Scrivi l'handoff e riparti pulita", ctxCompact: 'Compatta la conversazione',
  ctxWider: 'Passa alla finestra da 1M',
  ctxHandoffPrompt: "Scrivi l'handoff con /fable-director:handoff --here, poi io mando /clear.", conversation: 'Conversazione',
  enterSends: 'Invio manda · Maiusc+Invio a capo', back: 'Indietro',
}
