// I testi visibili, in un posto solo come strings.xml dell'app Android.
const pl = (n: number, one: string, other: string) => `${n === 1 ? one : other} · ${n}`
export const t = {
  summary: {
    waiting: (n: number) => pl(n, 'Ti aspetta', 'Ti aspettano'), finished: (n: number) => pl(n, 'Ha finito', 'Hanno finito'),
    working: (n: number) => pl(n, 'Al lavoro', 'Al lavoro'), still: (n: number) => pl(n, 'Ferma', 'Ferme'),
  } as Record<string, (n: number) => string>,
  closed: (n: number) => pl(n, 'Chiusa', 'Chiuse'), closedCat: (n: number) => `Chiuse · ${n}`, closedMore: (n: number) => `e altre ${n}`,
  outsideTitle: 'Fuori dalle sessioni', outsideSub: 'Quello che non sta in una sessione aperta',
  goal: 'Obiettivo', open: 'Apri i passaggi', close: 'Chiudi i passaggi',
  groups: { waiting: 'Ti aspetta', working: 'Al lavoro', idle: 'Ferma', closed: 'Chiuse' } as Record<string, string>,
  states: { waiting: 'domanda', busy: 'al lavoro', awaiting: 'in attesa', idle: 'ferma', gone: 'chiusa' } as Record<string, string>,
  // La «d» eufonica solo davanti alla stessa vocale (Preposition.kt): «Scrivi ad atlas-shop», «Scrivi a orbit-docs».
  writeTo: (name: string) => (name === 'master' ? 'Scrivi alla master' : `Scrivi ${/^[aàá]/i.test(name.trimStart()) ? 'ad' : 'a'} ${name}`),
  send: 'Invia', use: 'Usa', next: 'Prossimi', pick: 'Scegli una sessione dalla home',
  quota5h: (p: number) => `5h ${p}%`, ctx: (p: number) => `ctx ${p}%`, week: (p: number) => `sett. ${p}%`,
  stale: 'dato vecchio', demo: 'Dati di prova', updated: (h: string) => `${h} · aggiornato ora`,
  homeLast: (hm: string) => `Ultimo esito · ${hm}`, homeLastBare: 'Ultimo esito', listen: 'Ascolta',
  openConversation: 'Apri la conversazione', forYou: 'Per te', stepHint: 'Clic: nel campo · doppio clic: invia subito',
  fyContext: (name: string, p: number) => `Contesto di ${name} al ${p}%`, fyContextDetail: 'Conviene un handoff prima di continuare',
  fyHandoff: 'Handoff e riavvio', fyQuestion: (n: string) => `${n} ti chiede`, fyFinished: (n: string) => `${n} ha finito`,
  fyNightQueued: (n: number) => `Notte: ${n} in coda`, fyNightEmpty: 'Notte: niente in coda', fyNightDetail: 'Puoi lasciare un lavoro per stanotte',
  fyNext: (p: string) => `${p} · prossimo passo`, fyScheduled: (n: number) => (n === 1 ? '1 messaggio programmato' : `${n} messaggi programmati`),
  fyScheduledDetail: (hm: string) => `Il primo parte alle ${hm}`,
  fyAnswer: 'Rispondi', fyAdd: 'Aggiungi', fyStart: 'Avvia', fySee: 'Vedi', fyOpen: 'Apri',
  nightTitle: 'Aggiungi alla notte', nightProject: 'Progetto', nightPrompt: 'Cosa deve fare stanotte', nightAdd: 'Aggiungi', fyMore: (n: number) => `+${n} altre`,
  quota: (a: string, h5: number, w7: number) => `${a} ${h5}% · sett. ${w7}%`, quotaOld: (a: string) => `${a} · non aggiornata`,
  copy: 'Copia', readAloud: 'Leggi ad alta voce', stopReading: 'Ferma la lettura', outcomeLabel: 'Esito', textCut: 'testo accorciato dal PC',
  turnTokens: (n: number) => `${n} token scritti`, thinking: 'sta pensando',
  stepsCount: (n: number) => (n === 1 ? '1 passaggio' : `${n} passaggi`), stepsFailed: (n: number) => (n === 1 ? '1 fallito' : `${n} falliti`),
  origin: { pc: 'dal PC', watch: "dall'orologio", phone: 'dal telefono' } as Record<string, string>,
  chatStatus: {
    scheduled: (hm: string) => `parte alle ${hm}`, offline: () => 'senza rete, parte appena torna', uploading: () => "carico l'immagine",
    sending: () => 'invio', sent: () => 'inviato al PC', uncertain: () => 'in attesa del PC', failed: () => 'non consegnato',
    delivered: () => 'consegnato alla sessione', queued: () => 'in coda', working: () => 'preso in carico', done: () => 'elaborato',
  } as Record<string, (hm: string) => string>,
  questionHighRisk: "Rischio alto: tieni premuta l'opzione per rispondere", questionHold: 'Tieni premuto per confermare',
  chatAboutThis: 'Parliamone', allowAll: 'Consenti tutto', answerFree: 'Rispondi con parole tue',
  boxOpen: (x: string) => `Apri ${x}`, boxClose: (x: string) => `Chiudi ${x}`, boxAppend: 'Accoda nel campo', then: 'e poi',
  recurring: 'Ricorrenti', recurringOpen: 'Azioni ricorrenti', attach: 'Allega', attachGallery: 'Foto dalla galleria', attachCamera: 'Scatta una foto',
  attachFile: 'File', removeImage: "Togli l'immagine", reopen: 'Riapri', stop: 'Ferma', masterPlaceholder: 'Scrivi alla master',
  slashConfirmTitle: (c: string, n: string) => `Mandare /${c} a ${n}?`, slashConfirmClear: 'La conversazione della sessione si svuota: il contesto riparte da zero.',
  codeLabel: 'segue un blocco di codice', readingNow: 'IN LETTURA', readingOpen: (n: string) => `Torna a ${n}`,
  rateChange: (r: string) => `Velocità di lettura ${r}: tocca per cambiarla`, voiceChange: (v: string) => `Cambia voce, ora: ${v}`, voiceDefault: 'Predefinita del telefono',
  tabletState: { waiting: 'ti aspetta', finished: 'ha finito', working: 'al lavoro', still: 'ferma' } as Record<string, string>,
  tabletClose: (n: string) => `Togli ${n} dalle colonne`, tabletHomeLeft: 'Porta la home a sinistra', tabletHomeRight: 'Porta la home a destra',
  tabletResetWidths: 'Colonne di nuovo uguali', tabletDeskEmpty: 'Tocca una sessione nella home per aprirla qui; ne stanno fino a quattro, affiancate.',
  home: 'Casa', dockMaster: 'MASTER', more: 'Altro', cancel: 'Annulla',
  notes: { goal: 'Obiettivo', lowPriority: 'bassa priorità', lowPriorityOffered: 'bassa priorità proposta', noWindow: 'senza finestra' },
  modelTitle: 'Modello', effortTitle: 'Effort', choiceThisSession: 'Vale solo per questa sessione',
  quotaResetDesc: (p: number, r: string) => `Quota delle 5 ore al ${p}%, si azzera ${r}`,
  follow: 'Segui', unfollow: 'Non seguire', followSub: 'Una notifica quando finisce un turno', unfollowSub: 'Niente più notifiche a fine turno',
  askMaster: 'Fai controllare alla master', askMasterSub: 'La legge e ti risponde nella sua chat',
  askMasterPrompt: (n: string) => `Controlla la sessione ${n} e dimmi in breve a che punto è e se serve qualcosa da me.`,
  openInClaude: 'Apri in Claude', openInClaudeSub: "Continua nell'app Claude",
  menuExit: 'Chiudi la sessione', menuExitSub: 'Manda /exit, dopo una conferma',
  exitTitle: (n: string) => `Mandare /exit a ${n}?`, exitText: 'La sessione si chiude.', exitOk: 'Manda',
  ctxTitle: (p: number) => `Contesto ${p}%`, ctxHandoff: "Scrivi l'handoff e riparti pulita", ctxCompact: 'Compatta la conversazione',
  ctxWider: 'Passa alla finestra da 1M',
  ctxHandoffPrompt: "Scrivi l'handoff con /fable-director:handoff --here, poi riavviati pulita con claude-master restart --clean.", conversation: 'Conversazione',
  enterSends: 'Invio manda · Maiusc+Invio a capo', back: 'Indietro',
}
